### ISSUE TITLE
Loading additional files from dsk not working (CLOAD commands)

### ISSUE THREAD

**Issue by matthutchinson** [MiSTer-devel/Oric_MiSTer#4]
* [Invaders PSS](https://www.oric.org/software/invaders_pss_-1126.html)
* [Tap file](https://cdn.oric.org//games/software//i/invaders/invpss.tap)

During loading of `!INVADERS` the code tries to load other files from the inserted disk (using the CLOAD command) this fails/hangs without any displayed error.

Spoke with Jose Enguita/Chema he mentioned that:

> ...getting a tape program to work from a disk is not something easy. With multipart games it won't work properly. Also there seems to be a bug in the disk emulation and my Blake's 7 game gets stuck around the beginning of Episode 2.

**Comment by matthutchinson** [comment]
@rampa069 forgot to say, if you need help testing a fix for this (or anything else) on the core let me know.

**Comment by rampa069** [comment]
the cload isse this is not a problem with the core. is the same thing with the real machine. you need to modify the basic loader and change cload by load.

On the chemas game, is fixed now, just made a pull request.

**Comment by matthutchinson** [comment]
Thanks for the update, and your PR. 

Can you explain how to modify the basic loader?  Is there some way I can edit the BASIC code on the Oric core? Or use oric-dsk-manager (or the HxC Tool) to search/replace CLOAD commands with LOAD?

Its been 20 (or 30) years since I last touched BASIC :) but I'm up for trying to sort a fix out for this game (the first game I ever played on a computer).

**Comment by matthutchinson** [comment]
@rampa069 even a link to an old service manual or BASIC guide would help, or a high level description of the steps involved... I'm happy to invest the time to learn how to do this.

**Comment by matthutchinson** [comment]
OK, so after a lot of googling, trying different Oric tap and dsk tools I finally got this multi-part tap game to load.  
Posting here for anyone else who might find this useful.

This is a multipart Oric game, on tap format, so I needed to understand how the game's BASIC code loads files from the tap.

---

Here are the steps that worked for me:

1. First, get the tap file converted from `tap -> dsk -> edsk`

* Use [oric-dsk-manager](https://github.com/teiram/oric-dsk-manager) to convert from `tap -> dsk` (requires java, works on Windows/MacOS/Linux) drag the `tap` file into the UI, optionally tick the "boot" option, and save the `dsk` image.

![menuoric](https://user-images.githubusercontent.com/2095/135647518-2cbb6dd9-0df6-478d-8b3f-16df6ad12658.png)
 
* Convert this `dsk -> edsk` with [HxCFloppyEmulator](https://hxc2001.com/download/floppy_drive_emulator/) ([download here](https://hxc2001.com/download/floppy_drive_emulator/HxCFloppyEmulator_soft.zip)) (since this core only supports this CPC format) - Simply load the `dsk` from the previous step and export it as CPC DSK file 

2. Next use this [bas2tap](https://www.osdk.org/index.php?page=documentation&subpage=bas2tap) tool from the [Oric SDK](https://www.osdk.org/index.php?page=download) to convert original `tap` file to a raw text file with BASIC code.

```
   bas2tap -t2b invss.tap invss.txt
```

Open the generated text file and search for `CLOAD` commands.

**NOTE**: For a multipart tap, this command only extracted the BASIC code for the first file found on the tap. 
**But** that was enough for me to see how the game loaded. The resulting BASIC code was clearly just the game's loading screen and **I spotted two CLOAD commands**, that loaded the additional code from the tap to run the game.

<img width="452" alt="Screenshot 2021-10-01 at 16 42 19" src="https://user-images.githubusercontent.com/2095/135649021-2607e5be-fd40-4f7a-9299-9b97bb67de03.png">

3. With this information I booted this Oric core, mounted the `edsk` (from step 2 above) and hit F11 (to reboot and mount the dsk).

* type `dir` to list the dsk's contents and check the filename on the dsk (in this games case, the `INVADEOBJ` file was now `INVADEOB` on the edsk).
* input the following code in BASIC to load these files in the same order the games BASIC loading code did.

```
10 LOAD"INVADEOB"
20 LOAD"INVADERS2"
```

I typed `run` and the game loaded and worked! 😄 


---

**NOTE**: I had several unsuccessful attempts at converting the tap to a wav file with [tap2wav](https://www.osdk.org/index.php?page=documentation&subpage=tap2wav), and using this [ADC In](https://misterfpga.co.uk/product/adc-in-audio-tape-input-board/) board with a regular CLOAD command.  

* I found that the 11khz tap2wav option worked best, playing the file from VLC on my Mac laptop headphone out (max volume).
* CLOAD worked with [the resulting file](https://github.com/MiSTer-devel/Oric_MiSTer/files/7268499/invpss-11khz.wav.zip), but appeared to only load the loading screen.
* The file was pretty short (1 min duration), which makes me think that the tap2wav tool is only converting the first file found on the tap (much like the bas2txt tool)

**Comment by matthutchinson** [comment]
Closing this issue for now, to have the core support tap files natively seems more like a feature request than a bug, and an issue with tooling rather than this core.

With a better `tap2wav` tool that supported multipart taps, we could use the ADC in (RX pin) to load via audio wav's anyway.
